import{a as m,S as v,i as n}from"./assets/vendor-CrlV4O_2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();m.defaults.baseURL="https://pixabay.com/api/";const S="50358414-c92bcdcb4052cd5a2ab490d79",d=15;async function f(r,e){const o={params:{key:S,q:r,page:e,per_page:d,image_type:"photo",orientation:"horizontal",safesearch:!0}};try{return(await m.get("",o)).data}catch(a){throw console.log(a),a}}const g=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-btn"),P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function p(r){const e=r.map(o=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${o.largeImageURL}">
                <img
                    class="gallery-image"
                    src="${o.webformatURL}"
                    alt="${o.tags}"
                />
            </a>
            <div class="image-info">
                <p><b>Likes:</b> ${o.likes}</p>
                <p><b>Views:</b> ${o.views}</p>
                <p><b>Comments:</b> ${o.comments}</p>
                <p><b>Downloads:</b> ${o.downloads}</p>
            </div>
        </li>`).join("");g.insertAdjacentHTML("beforeend",e),P.refresh()}function R(){g.innerHTML=""}function b(){y.classList.add("active")}function L(){y.classList.remove("active")}function i(){h.classList.add("hidden")}function q(){h.classList.remove("hidden")}function E(){const r=document.querySelector(".gallery-item");if(!r)return;const e=r.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}const w=document.querySelector(".form"),$=w.elements["search-text"];let c,l=0;w.addEventListener("submit",B);async function B(r){if(r.preventDefault(),c=$.value.trim(),c===""){n.warning({message:"Please enter a search term!",position:"topRight"});return}b(),R();try{l=1;const e=await f(c,l);if(e.hits.length===0){n.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight"}),i();return}p(e.hits),e.hits.length<d?(i(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"})):q()}catch{n.error({message:"Something went wrong. Please try again later.",position:"bottomRight"})}finally{L()}}h.addEventListener("click",O);async function O(r){r.preventDefault(),b();try{l+=1;const e=await f(c,l);if(e.hits.length===0){i(),n.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight"});return}p(e.hits),E(),e.hits.length<d&&(i(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}))}catch{n.error({message:"Something went wrong. Please try again later.",position:"bottomRight"}),i()}finally{L()}}
//# sourceMappingURL=index.js.map
