import{a as f,S as P,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();f.defaults.baseURL="https://pixabay.com/api/";const S="50358414-c92bcdcb4052cd5a2ab490d79",m=15;async function h(r,e){const o={params:{key:S,q:r,page:e,per_page:m,image_type:"photo",orientation:"horizontal",safesearch:!0}};try{return(await f.get("",o)).data}catch(i){throw console.log(i),i}}const g=document.querySelector(".gallery"),y=document.querySelector(".loader"),d=document.querySelector(".load-btn"),R=new P(".gallery a",{captionsData:"alt",captionDelay:250});function p(r){const e=r.map(o=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${o.largeImageURL}">
                <img
                    class="gallery-image"
                    src="${o.webformatURL}"
                    alt="${o.tags}"
                />
            </a>
            <div class="image-info">
                <p><b>Likes:</b> ${o.likes}</p>
                <p><b>Views:</b> ${o.views}</p>
                <p><b>Comments:</b> ${o.comments}</p>
                <p><b>Downloads:</b> ${o.downloads}</p>
            </div>
        </li>`).join("");g.insertAdjacentHTML("beforeend",e),R.refresh()}function q(){g.innerHTML=""}function b(){y.classList.add("active")}function L(){y.classList.remove("active")}function B(){d.classList.add("hidden")}function E(){d.classList.remove("hidden")}function $(){const r=document.querySelector(".gallery-item");if(!r)return;const e=r.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}const w=document.querySelector(".form"),x=w.elements["search-text"];let c,s=0,l=0;w.addEventListener("submit",M);async function M(r){if(r.preventDefault(),c=x.value.trim(),c===""){a.warning({message:"Please enter a search term!",position:"topRight"});return}b(),q();try{s=1;const e=await h(c,s);if(l=Math.ceil(e.totalHits/m),v(),s===l){a.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"});return}if(e.hits.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight"});return}p(e.hits)}catch{a.error({message:"Something went wrong. Please try again later.",position:"bottomRight"})}finally{L()}}d.addEventListener("click",O);async function O(r){r.preventDefault(),b();try{s+=1,v();const e=await h(c,s);if(e.hits.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight"});return}if(s===l){a.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"});return}p(e.hits),$()}catch{a.error({message:"Something went wrong. Please try again later.",position:"bottomRight"})}finally{L()}}function v(){s<l?E():B()}
//# sourceMappingURL=index.js.map
